config/routes.rb
Rails.application.routes.draw do

   root 'students#index'

     resources :students do
       resources :comments
     end   

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :comments
	validates :name, presence: true #, name: true 
	validates :name, length: {minimum: 2}, format: {with: /\A[a-zA-Z]+\z/, message: "only allows letters..." }, uniqueness: { case_sensitive: false }, unless: "name.blank?"
	validates :roll_no, presence: true
	validates :roll_no, numericality: true, unless: "roll_no.blank?"
	validates :student_class, presence: true
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
		@student = Student.find(params[:id])
		#raise @student.inpect
		@comment = @student.comments.new(comment_params)
		if @comment.save
			redirect_to student_path(@student)
		end		
	end


	private

	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def index
		@students = Student.all
	end

	def show
		@student = Student.find(params[:id])
		#raise @student.inspect 
	end

	def new
		@student = Student.new
	end

	def create
		#raise student_params.inspect
		@student = Student.new(student_params)
		if @student.save
			redirect_to students_path
		else
			render "new"
		end
	end

	def edit
		@student = Student.find(params[:id])
	end
	
	def update
		#render plain: params[:student].inspect
		@student = Student.find(params[:id])
		#raise @student.inspect
		if @student.update(student_params)
			redirect_to student_path(@student)
		else
			render "edit"
		end
	end

	def destroy
		@student = Student.find(params[:id])
		if @student.destroy
			redirect_to students_path
		else
			redirect_to student_path(@student)
		end
	end

	private

	def student_params
		params.require(:student).permit(:name, :roll_no, :student_class, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentsDetails</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "Students", students_path, class: "navbar-brand" %>
		</div>	
	</div>	
</div>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
<% if @student.errors.any? %>
	<h2><%= pluralize(@student.errors.count, "error") %> Prohibited this article from being saved: </h2>
	<ul>
		<% @student.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>
	<p><b> Name: </b></p><%= f.text_field :name %>
	<p><b> Roll no: </b></p><%= f.text_field :roll_no %>
	<p><b> Class: </b></p><%= f.text_field :student_class %>
	<p><b> Description: </b></p><%= f.text_area :description %>
	<p><%= f.submit %></p>
<% end %>

app/views/students/edit.html.erb
<div class="container">
	<h1>Edit Student <%= link_to "Back", student_path(@student), class: "btn btn-style pull-right" %></h1><hr/>
	<div class="col-md-8 col-md-offset-2">	
		<div class="student-show">
			<%= render "form" %>
		</div>	
	</div>	
</div>

app/views/students/index.html.erb
<div class="container">	

		<h1>Students<%= link_to "Add Student", new_student_path, class: "btn btn-style pull-right" %>
		</h1>	<hr/>

		<% @students.find_each do |student| %>	
		<div class="col-md-4">
			<div class="student">
				<h2 class="student-title"><%= student.name %></h2>
				<%= link_to "View Details", student_path(student), class: "btn-custom"%>
			</div>	
		</div>	
		<% end %>		
</div>	

app/views/students/new.html.erb
<div class="container">
	<h1>Add student <%= link_to "Back", students_path, class: "btn btn-style pull-right"  %></h1><hr/>
	<div class="col-md-8 col-md-offset-2">
		<div class="student-show">
			<%= render "form" %>
		</div>	
	</div>	
</div>	

app/views/students/show.html.erb
<div class="container">			
		<h1>Details 
				 <%= link_to "Back", students_path, class: "pull-right btn btn-style"  %>	
				 <%= link_to "Delete", student_path(@student), method: :delete, data: { confirm: "Are you sure want to delete?" } , class: "pull-right btn btn-style" %>
				 <%= link_to "Edit", edit_student_path(@student), class: "pull-right btn btn-style" %>
		</h1><hr/>
		<div class="col-md-6 col-md-offset-3">
		 <div class="student-show">
		 	<p><b>Name:</b> <%= @student.name %></p> 
			<p><b>Roll no:</b> <%= @student.roll_no %></p>
			<p><b>Class:</b> <%= @student.student_class %></p>
			<p><b>Description:</b> <%= @student.description %></p><hr/>

			<h4>Comments</h4>
			<% @student.comments.each do |comment| %>
				
				<p>
					<strong>Commenter:</strong>	
					<%= comment.commenter %>
				</p>
				<p>
					<strong>Comment:</strong>
					<%= comment.body %>
				</p>	
			<% end %><hr/>	

			<u><h4>Add a comment:</h4></u>
			<%= form_for([@student, @student.comments.build]) do |f| %>
			  <p>
			    <%= f.label :commenter %><br>
			    <%= f.text_field :commenter %>
			  </p>
			  <p>
			    <%= f.label :body %><br>
			    <%= f.text_area :body %>
			  </p>
			  <p>
			    <%= f.submit %>
			  </p>
			<% end %>
		</div>	
	</div>	
   </div>	
</div>		